- name: start static content
  shell: nohup ./serve >/dev/null &
  args:
    chdir: ~/infra-problem/front-end/public

- name: wait until the app is running
  wait_for:
    port: 8000
    timeout: 60

- name: readiness probe for service
  uri:
    url: http://localhost:8000
    method: GET
    status_code: 200

- name: start frontend
  shell: nohup java -jar front-end.jar >/dev/null &
  args:
    chdir: ~/infra-problem/build
  environment:
    APP_PORT: '8080'
    STATIC_URL: 'http://localhost:8000'
    NEWSFEED_SERVICE_URL: 'http://localhost:8081'
    QUOTE_SERVICE_URL: 'http://localhost:8082'
    NEWSFEED_SERVICE_TOKEN: 'T1&eWbYXNWG1w1^YGKDPxAWJ@^et^&kX'

- name: wait until the app is running
  wait_for:
    port: 8080
    timeout: 60

- name: readiness probe for service
  uri:
    url: http://localhost:8080/ping
    method: GET
    status_code: 200

