- name: start static content
  shell: nohup ./serve.py >/dev/null &
  args:
    chdir: ~/infra-problem/front-end/public

- name: wait until the app is running
  wait_for:
    port: '{{static_content_port}}'
    timeout: 60

- name: readiness probe for service
  uri:
    url: '{{static_content_url}}'
    method: GET
    status_code: 200

- name: start frontend
  shell: nohup java -jar front-end.jar >/dev/null &
  args:
    chdir: ~/infra-problem/build
  environment:
    APP_PORT: '{{frontend_app_port}}'
    STATIC_URL: '{{static_content_url}}'
    NEWSFEED_SERVICE_URL: '{{newsfeed_service_url}}'
    QUOTE_SERVICE_URL: '{{quotes_service_url}}'
    NEWSFEED_SERVICE_TOKEN: '{{newsfeed_service_token}}'

- name: wait until the app is running
  wait_for:
    port: '{{frontend_app_port}}'
    timeout: 60

- name: readiness probe for service
  uri:
    url: '{{frontend_service_url}}/ping'
    method: GET
    status_code: 200

