- name: testing that we are in an stable build
  shell: nohup `APP_PORT=8080 java -jar front-end.jar` >/dev/null &
  args:
    chdir: ~/infra-problem/build

- name: wait until the app is running
  wait_for:
    port: 8080
    timeout: 60

- name: readiness probe for service
  uri:
    url: http://localhost:8080/ping
    method: GET
    status_code: 200

