- name: start quotes
  shell: nohup java -jar quotes.jar >/dev/null &
  args:
    chdir: ~/infra-problem/build
  environment:
    APP_PORT: '8082'

- name: wait until the app is running
  wait_for:
    port: 8082
    timeout: 60

- name: readiness probe for service
  uri:
    url: http://localhost:8082/ping
    method: GET
    status_code: 200