- name: start quotes
  shell: nohup java -jar quotes.jar >/dev/null &
  args:
    chdir: ~/infra-problem/build
  environment:
    APP_PORT: '{{quotes_app_port}}'

- name: wait until the app is running
  wait_for:
    port: '{{quotes_app_port}}'
    timeout: 60

- name: readiness probe for service
  uri:
    url: '{{quotes_service_url}}/ping'
    method: GET
    status_code: 200