- name: Ansible provisioner
  hosts: all
  roles:
  - bootstrap
#  - build-services
  - frontend
  - newsfeed
  - quotes
  vars:
  - frontend_app_port: 8080
  - newsfeed_app_port: 8081
  - quotes_app_port: 8082
  - static_url: 'http://localhost:8000'
  - frontend_service_url: 'http://localhost:{{frontend_app_port}}'
  - newsfeed_service_url: 'http://localhost:{{newsfeed_app_port}}'
  - quotes_service_url: 'http://localhost:{{quotes_app_port}}'
