- name: start newsfeed
  shell: nohup java -jar newsfeed.jar >/dev/null &
  args:
    chdir: ~/infra-problem/build
  environment:
    APP_PORT: '{{newsfeed_app_port}}'

- name: wait until the app is running
  wait_for:
    port: '{{newsfeed_app_port}}'
    timeout: 60

- name: readiness probe for service
  uri:
    url: '{{newsfeed_service_url}}/ping'
    method: GET
    status_code: 200

